Repository despensa-app/despensa-rest-api, pull requests merged in 2024-10, with the labels that each got.

#15 Add build file for Github Action #10
  .github/workflows/build.yml
Labels: hacktoberfest-accepted

#19 [FEAT] Create xml file docker compose (despensa-rest-api)
  .run/docker compose (despensa-rest-api).run.xml
Labels: hacktoberfest-accepted

#21 feat: Add Sample Shopping Lists
  src/main/resources/db/data.sql
Labels: hacktoberfest-accepted

#17 fix: update type in Users database to Long (#8)
  src/main/java/dev/nmarulo/depensaapp/app/authentication/dtos/AuthenticationRes.java
  src/main/java/dev/nmarulo/depensaapp/app/users/User.java
  src/main/java/dev/nmarulo/depensaapp/app/users/UserController.java
  src/main/java/dev/nmarulo/depensaapp/app/users/UserRepository.java
  src/main/java/dev/nmarulo/depensaapp/app/users/UserService.java
  src/main/java/dev/nmarulo/depensaapp/app/users/dtos/FindByIdUserRes.java
  src/main/resources/db/schema.sql
Labels: hacktoberfest-accepted

#20 Create labeler.yml - configuration for github action to evaluate PR sizes
  .github/workflows/labeler.yml
Labels: hacktoberfest-accepted

#26 Create dockerdev profile #5 done
  .run/docker compose.run.xml
  Dockerfile
  src/main/resources/application-dockerdev.properties
Labels: hacktoberfest-accepted

#25 Updated boxfuse properties file
  src/main/resources/application-boxfuse.properties
Labels: hacktoberfest-accepted

#27 Implemented Audit annotations for the `ShoppingList` entity
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingList.java
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListService.java
  src/main/java/dev/nmarulo/depensaapp/configuration/JpaConfig.java
Labels: hacktoberfest-accepted

#16 Issue7
  src/main/java/dev/nmarulo/depensaapp/app/products/Product.java
  src/main/java/dev/nmarulo/depensaapp/app/products/ProductAdminController.java
  src/main/java/dev/nmarulo/depensaapp/app/products/ProductAdminService.java
  src/main/java/dev/nmarulo/depensaapp/app/products/ProductRepository.java
  src/main/java/dev/nmarulo/depensaapp/app/products/dtos/FindAllProductRes.java
  src/main/java/dev/nmarulo/depensaapp/app/products/dtos/FindAllShoppingListProductRes.java
  src/main/java/dev/nmarulo/depensaapp/app/products/dtos/ProductAdminRes.java
  src/main/java/dev/nmarulo/depensaapp/app/products/dtos/SaveShoppingListProductReq.java
  src/main/java/dev/nmarulo/depensaapp/app/products/dtos/SaveShoppingListProductRes.java
  src/main/java/dev/nmarulo/depensaapp/app/productshoppinglist/ProductHasShoppingListPK.java
  src/main/java/dev/nmarulo/depensaapp/app/productshoppinglist/ProductHasShoppingListRepository.java
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListController.java
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListService.java
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/dtos/DeleteProductsShoppingListReq.java
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/dtos/FindByIdShoppingListRes.java
  src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/dtos/UpdateShoppingListReq.java
  src/main/resources/db/schema.sql
Labels: hacktoberfest-accepted, Size: S

#32 #6 Translate readme file into English
  README.md
  translations/README.en.md
Labels: hacktoberfest-accepted, Size: M

#33 Fix #24 : add missing JSR-305 dependency to resolve annotation processing …
  pom.xml
Labels: hacktoberfest-accepted, Size: XS

#38 Feat: Add randomImage method
  src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java
Labels: hacktoberfest-accepted, Size: XS

#39 Feat: Create the randomFuture method
  src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/unitytypes/UnitTypeServiceTestUtil.java
Labels: hacktoberfest-accepted, Size: S

#40 feat: Add randomPast method (ref #37)
  src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/unitytypes/UnitTypeServiceTestUtil.java
Labels: Size: S

#41 Implemented randomBigDecimal method
  src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java
  src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java
Labels: hacktoberfest-accepted, Size: S

#42 Add custom JWT error messages for authentication failures
  src/main/java/dev/nmarulo/depensaapp/security/JwtAuthenticationEntryPoint.java
  src/main/java/dev/nmarulo/depensaapp/security/WebSecurityConfig.java
Labels: hacktoberfest-accepted, Size: S
